Repository googleapis/java-service-management, pull requests merged in 2021-05, with the labels that each got.

#38 feat: promote to 1.0.0
  .repo-metadata.json
Labels: automerge, cla: yes

#39 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#42 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: automerge, cla: yes, context: none

#43 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#44 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: automerge, cla: yes

#45 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#49 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#50 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes, kokoro:force-run

#51 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#53 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#56 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#61 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes
